apiVersion: v1
kind: Service
metadata:
 name: resource-server
 labels:
   app: resource-server
spec:
 ports:
 - port: 8082
 selector:
   app: ecom-res
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ecom-res-app
 labels:
   app: ecom-res
spec:
 replicas: 1
 selector:
   matchLabels:
     app: ecom-res
 template:
   metadata:
     labels:
       app: ecom-res
   spec:
     containers:
     - name: keyist-resserver
       image: gouthamrajen/resource_server:latest
       ports:
       - containerPort: 8082
       env:
       - name: SPRING_DATASOURCE_URL
         value: jdbc:mysql://mysql:3306/keyist?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
       - name: SPRING_DATASOURCE_USERNAME
         value: keyistuser
       - name: SPRING_DATASOURCE_PASSWORD
         value: keyistpassword
       - name: SECURITY_AUTH_URL
         value: http://authorization_server:8081/oauth/check_token
       - name: SECURITY_AUTH_CLIENT_ID
         value: test
       - name: SECURITY_AUTH_CLIENT_PASSWORD
         value: test