apiVersion: v1
kind: Service
metadata:
 name: ecom-app-auth-svc
 labels:
   app: ecom-auth
spec:
 ports:
 - port: 8081
 selector:
   app: ecom-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ecom-auth-app
 labels:
   app: ecom-auth
spec:
 replicas: 1
 selector:
   matchLabels:
     app: ecom-auth
 template:
   metadata:
     labels:
       app: ecom-auth
   spec:
     containers:
     - name: keyist-authserver
       image: gouthamrajen/authorization_server:latest
       ports:
       - containerPort: 8081
       env:
       - name: SPRING_DATASOURCE_URL
         value: jdbc:mysql://mysql:3306/keyist?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
       - name: SPRING_DATASOURCE_USERNAME
         value: keyistuser
       - name: SPRING_DATASOURCE_PASSWORD
         value: keyistpassword
