apiVersion: v1
kind: Service
metadata:
 name: client
 labels:
   app: client
spec:
 type: NodePort
 ports:
 - port: 80
   targetPort: 4200
 selector:
   app: ecom-fe
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ecom-fe-app
 labels:
   app: ecom-fe
spec:
 replicas: 1
 selector:
   matchLabels:
     app: ecom-fe
 template:
   metadata:
     labels:
       app: ecom-fe
   spec:
     containers:
     - name: keyist-feserver
       image: gouthamrajen/client:latest
       ports:
       - containerPort: 80