apiVersion: v1
kind: Service
metadata:
 name: mysql
 labels:
   app: mysql
spec:
 ports:
 - port: 3306
 selector:
   app: ecom-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ecom-db-app
 labels:
   app: ecom-db
spec:
 replicas: 1
 selector:
   matchLabels:
     app: ecom-db
 template:
   metadata:
     labels:
       app: ecom-db
   spec:
     containers:
     - name: keyist-dbserver
       image: mysql
       ports:
       - containerPort: 3306